import { Language, WorkerFeature } from './types';

export const LANGUAGES: Language[] = [
  {
    code: 'en',
    nativeName: 'English',
    englishName: 'English',
    audioPrompt: 'Please choose English language'
  },
  {
    code: 'te',
    nativeName: 'తెలుగు',
    englishName: 'Telugu',
    audioPrompt: 'దయచేసి తెలుగు భాషను ఎంచుకోండి'
  },
  {
    code: 'hi',
    nativeName: 'हिन्दी',
    englishName: 'Hindi',
    audioPrompt: 'कृपया हिन्दी भाषा चुनें'
  },
  {
    code: 'kn',
    nativeName: 'ಕನ್ನಡ',
    englishName: 'Kannada',
    audioPrompt: 'ದಯವಿಟ್ಟು ಕನ್ನಡ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ'
  },
  {
    code: 'ta',
    nativeName: 'தமிழ்',
    englishName: 'Tamil',
    audioPrompt: 'தயவுசெய்து தமிழ் மொழியைத் தேர்ந்தெடுக்கவும்'
  },
  {
    code: 'ml',
    nativeName: 'മലയാളം',
    englishName: 'Malayalam',
    audioPrompt: 'ദയവായി മലയാളം ഭാഷ തിരഞ്ഞെടുക്കുക'
  },
  {
    code: 'bn',
    nativeName: 'বাংলা',
    englishName: 'Bengali',
    audioPrompt: 'অনুগ্রহ করে বাংলা ভাষা নির্বাচন করুন'
  },
  {
    code: 'mr',
    nativeName: 'मराठी',
    englishName: 'Marathi',
    audioPrompt: 'कृपया मराठी भाषा निवडा'
  },
  {
    code: 'or',
    nativeName: 'ଓଡ଼ିଆ',
    englishName: 'Odia',
    audioPrompt: 'ଦୟାକରି ଓଡ଼ିଆ ଭାଷା ବାଛନ୍ତୁ'
  },
  {
    code: 'pa',
    nativeName: 'ਪੰਜਾਬੀ',
    englishName: 'Punjabi',
    audioPrompt: 'ਕਿਰਪਾ ਕਰਕੇ ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਦੀ ਚੋਣ ਕਰੋ'
  }
];

export const WORKER_FEATURES: WorkerFeature[] = [
  {
    id: 'emergency',
    nameKey: 'Emergency / 24x7 Help',
    englishName: 'Emergency Help',
    nativeName: 'ఆపత్కాల సహాయం / आपातकालीन सहायता',
    icon: 'PhoneCall',
    color: 'bg-red-50 text-red-600 border-red-200 hover:bg-red-100',
    description: 'Call for immediate medical assistance or contact HealthBridge support.'
  },
  {
    id: 'symptoms',
    nameKey: 'Symptom Checker',
    englishName: 'Symptoms Checker',
    nativeName: 'లక్షణాలు తనిఖీ / लक्षण जाँच',
    icon: 'Activity',
    color: 'bg-amber-50 text-amber-600 border-amber-200 hover:bg-amber-100',
    description: 'Select your symptoms using easy pictures and simple guides.'
  },
  {
    id: 'hospitals',
    nameKey: 'Nearby Hospitals',
    englishName: 'Nearby Hospitals',
    nativeName: 'సమీప ఆసుపత్రులు / पास के अस्पताल',
    icon: 'MapPin',
    color: 'bg-blue-50 text-blue-600 border-blue-200 hover:bg-blue-100',
    description: 'Find local clinics and government hospitals near your current location.'
  },
  {
    id: 'appointments',
    nameKey: 'My Appointments',
    englishName: 'Appointments',
    nativeName: 'నా అపాయింట్‌మెంట్‌లు / मेरी अपॉइंटमेंट',
    icon: 'Calendar',
    color: 'bg-emerald-50 text-emerald-600 border-emerald-200 hover:bg-emerald-100',
    description: 'Check your upcoming appointments with doctors and mobile clinics.'
  },
  {
    id: 'camps',
    nameKey: 'Medical Camps',
    englishName: 'Medical Camps',
    nativeName: 'ఉచిత వైద్య శిబిరాలు / चिकित्सा शिविर',
    icon: 'HeartHandshake',
    color: 'bg-sky-50 text-sky-600 border-sky-200 hover:bg-sky-100',
    description: 'View schedule of upcoming free health checkup camps in your area.'
  },
  {
    id: 'prescriptions',
    nameKey: 'Prescriptions',
    englishName: 'Prescriptions',
    nativeName: 'మందుల చీటి / दवा की पर्ची',
    icon: 'FileText',
    color: 'bg-purple-50 text-purple-600 border-purple-200 hover:bg-purple-100',
    description: 'View digital prescriptions written by your doctors with voice guides.'
  },
  {
    id: 'history',
    nameKey: 'Medical History',
    englishName: 'Medical History',
    nativeName: 'వైద్య చరిత్ర / चिकित्सा इतिहास',
    icon: 'FolderHeart',
    color: 'bg-indigo-50 text-indigo-600 border-indigo-200 hover:bg-indigo-100',
    description: 'Keep record of vaccines, reports, and previous health conditions.'
  },
  {
    id: 'chat',
    nameKey: 'Multilingual Chat',
    englishName: 'Voice Chat Support',
    nativeName: 'వాయిస్ చాట్ / आवाज चैट सहायता',
    icon: 'MessageSquareText',
    color: 'bg-teal-50 text-teal-600 border-teal-200 hover:bg-teal-100',
    description: 'Speak or type in your language to ask health questions.'
  }
];

// Transliteration helper for Proper Nouns per instructions
export function getLocalizedProperNoun(englishName: string, langCode: string): string {
  const table: Record<string, Record<string, string>> = {
    'Athreya Hospital': {
      te: 'ఆత్రేయ హాస్పిటల్',
      hi: 'आत्रेय अस्पताल',
      kn: 'ಆತ್ರೇಯ ಆಸ್ಪತ್ರೆ',
      ta: 'ஆத்ரேயா மருத்துவமனை',
      ml: 'ಆത്രേയ ഹോസ്പിറ്റൽ',
      bn: 'আত্রেয় হাসপাতাল',
      mr: 'आत्रेय रुग्णालय',
      or: 'ଆତ୍ରେୟ ହସ୍ପିଟାଲ୍',
      pa: 'ਆਤ੍ਰੇਯ ਹਸਪਤਾਲ',
    },
    'Aditi Hospital': {
      te: 'అదితి హాస్పిటల్',
      hi: 'अदिति अस्पताल',
    },
    'Government Hospital Anekal': {
      te: 'ప్రభుత్వ హాస్పిటల్ అనేకల్',
      hi: 'सरकारी अस्पताल अनेकल',
    },
    'Raghu Hospital': {
      te: 'రఘు హాస్పిటల్',
      hi: 'रघु अस्पताल',
    },
    'Demo Doctor Ramesh Kumar': {
      te: 'డెమో డాక్టర్ రమేష్ కుమార్',
      hi: 'डेमो डॉक्टर रमेश कुमार',
    },
    'Demo Doctor Anita Desai': {
      te: 'డెమో డాక్టర్ అనిత దేశాయ్',
      hi: 'डेमो डॉक्टर अनीता देसाई',
    },
    'Demo Doctor Susan Varghese': {
      te: 'డెమో డాక్టర్ సుసాన్ వర్గీస్',
      hi: 'डेमो डॉक्टर सुसान वर्गीस',
    },
    'Demo Doctor Rajesh Patil': {
      te: 'డెమో డాక్టర్ రాజేష్ పాటిల్',
      hi: 'डेमो डॉक्टर राजेश पाटिल',
    },
    'Demo Doctor Rajeev Sethi': {
      te: 'డెమో డాక్టర్ రాజీవ్ సేథి',
      hi: 'डेमो डॉक्टर राजीव सेठी',
    },
    'Demo Doctor Maya Rao': {
      te: 'డెమో డాక్టర్ మాయా రావు',
      hi: 'डेमो डॉक्टर माया राव',
    },
    'Demo Doctor Suresh Kumar': {
      te: 'డెమో డాక్టర్ సురేష్ కుమార్',
      hi: 'डेमो डॉक्टर सुरेश कुमार',
    },
    'Demo Doctor Vivek Sharma': {
      te: 'డెమో డాక్టర్ వివేక్ శర్మ',
      hi: 'डेमो डॉक्टर विवेक शर्मा',
    },
    'City Civil Government Hospital': {
      te: 'సిటీ సివిల్ గవర్నమెంట్ హాస్పిటల్',
      hi: 'सिटी सिविल गवर्नमेंट हॉस्पिटल',
      kn: 'ಸಿಟಿ సిವಿಲ್ ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆ',
      ta: 'சிட்டி సిவில் அரசு மருத்துவமனை',
      ml: 'സിറ്റി സിവിൽ ഗവൺമെന്റ് ഹോസ്പിറ്റൽ',
      bn: 'সিটি సిভিল সরকারি হাসপাতাল',
      mr: 'सिटी सिव्हिल सरकारी रुग्णालय',
      or: 'ସିଟି ସିଭିଲ୍ ସରକାରୀ ହସ୍ପିଟାଲ୍',
      pa: 'ਸਿਟੀ ਸਿਵਲ ਸਰਕਾਰੀ ਹਸਪਤਾਲ',
    },
    'Red Cross Community Clinic': {
      te: 'రెడ్ క్రాస్ కమ్యూనిటీ క్లినిక్',
      hi: 'रेड क्रॉस कम्युनिटी क्लीनिक',
      kn: 'ರೆಡ್ ಕ್ರಾಸ್ ಕಮ್ಯುನಿಟಿ ಕ್ಲಿನಿಕ್',
      ta: 'ரெட் கிராஸ் சமூக கிளினிக்',
      ml: 'റെഡ് ക്രോസ് കമ്മ്യൂണിറ്റി ക്ലിനിക്',
      bn: 'রেडクロス কমিউনিটি ক্লিনিক',
      mr: 'रेड क्रॉस कम्युनिटी क्लिनिक',
      or: 'ରେଡ୍ କ୍ରସ୍ କମ୍ୟୁନିଟି କ୍ଲିନିକ୍',
      pa: 'ਰੇਡ ਕਰਾਸ ਕਮਿਊਨਿਟੀ ਕਲੀਨਿਕ',
    },
    'Apex Migrant Health Centre': {
      te: 'అపెక్స్ మైగ్రెంట్ హెల్త్ సెంటర్',
      hi: 'एपेक्स माइग्रेंट हेल्थ सेंटर',
      kn: 'ಅಪೆಕ್ಸ್ ಮೈಗ್ರೆಂಟ್ ಹೆಲ್ತ್ ಸೆಂಟರ್',
      ta: 'அபெக்ஸ் புலம்பெயர்ந்தோர் சுகாதார மையம்',
      ml: 'അപെക്സ് മൈഗ്രന്റ് ഹെൽത്ത് സെന്റർ',
      bn: 'অ্যাপেক্স মাইগ্রেন্ট হেলথ সেন্টার',
      mr: 'अपेक्स मायग्रंट हेल्थ सेंटर',
      or: 'ଆପେକ୍ସ ମାଇଗ୍ରେଣ୍ଟ ହେଲ୍ଥ ସେଣ୍ଟର',
      pa: 'ਐਪੈਕਸ ਮਾਈਗ੍ਰੈਂਟ ਹੈਲਥ ਸੈਂਟਰ',
    },
    'Dr. Ramesh Kumar': {
      te: 'డా. రమేష్ కుమార్',
      hi: 'डॉ. रमेश कुमार',
      kn: 'ಡಾ. ರಮೇಶ್ ಕುಮಾರ್',
      ta: 'டாக்டர் ரமேஷ் குமார்',
      ml: 'ഡോ. രമേഷ് കുമാർ',
      bn: 'ডা. রমেশ কুমার',
      mr: 'डॉ. रमेश कुमार',
      or: 'ଡଃ ରମେଶ କୁମାର',
      pa: 'ਡਾ. ਰਮੇਸ਼ ਕੋਮਾਰ',
    },
    'Dr. Anita Desai': {
      te: 'డా. అనిత దేశాయ్',
      hi: 'डॉ. अनीता देसाई',
      kn: 'ಡಾ. ಅನಿತಾ ದೇಸಾಯಿ',
      ta: 'டாக்டர் அனிதா தேசாய்',
      ml: 'ഡോ. അനിത ദേശായി',
      bn: 'ডা. অনিতা দেসাই',
      mr: 'डॉ. अनिता देसाई',
      or: 'ଡଃ ଅନିତା ଦେଶାଇ',
      pa: 'ਡਾ. ਅਨੀਤਾ ਦੇਸਾਈ',
    },
    'Lions Club & HealthBridge': {
      te: 'లయన్స్ క్లబ్ & హెల్త్‌బ్రిడ్జ్',
      hi: 'लायंस क्लब एंड हेल्थब्रिज',
      kn: 'ಲಯನ್ಸ್ ಕ್ಲಬ್ ಮತ್ತು ಹೆಲ್ತ್ ಬ್ರಿಡ್ಜ್',
      ta: 'லயன்ஸ் கிளப் & ஹெல்த்பிரிட்ஜ்',
      ml: 'ലയൺസ് ക്ലബ് & ഹെൽത്ത് ബ്രിഡ്ജ്',
      bn: 'লায়ন্স ক্লাব এবং হেলথব্রিজ',
      mr: 'लायन्स क्लब आणि हेल्थब्रिज',
      or: 'ଲାୟନ୍ସ କ୍ଲବ୍ ଏବଂ ହେଲ୍ଥବ୍ରିଜ୍',
      pa: 'ਲਾਇਨਜ਼ ਕਲੱਬ ਅਤੇ ਹੈਲਥਬ੍ਰਿਜ',
    },
    'Asha Workers & Red Cross': {
      te: 'ఆశా వర్కర్లు & రెడ్ క్రాస్',
      hi: 'आशा वर्कर्स एंड रेड क्रॉस',
      kn: 'ಆಶಾ ಕಾರ್ಯಕರ್ತರು మరియు రెడ్ క్రాస్',
      ta: 'ஆஷா பணியாளர்கள் & ரெட் கிராஸ்',
      ml: 'ആശ വർക്കർമാർ & റെഡ് ക്രോസ്',
      bn: 'আশা কর্মী এবং রেড ক্রস',
      mr: 'आशा वर्कर्स आणि रेड क्रॉस',
      or: 'ଆଶା କର୍ମୀ ଏବଂ ରେଡ୍ କ୍ରସ୍',
      pa: 'ਆਸ਼ा ਵਰਕਰ ਅਤੇ ਰੇਡ ਕਰਾਸ',
    }
  };

  const translations = table[englishName];
  if (translations && translations[langCode]) {
    return `${englishName} — ${translations[langCode]}`;
  }
  return englishName;
}

// Complete dictionary with high-quality translations for all 10 languages
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    back: 'Back',
    emergency_title: 'Emergency Response Support',
    emergency_desc: 'If you or someone near you needs urgent care, press the button below to trigger assistance.',
    symptoms_title: 'Easy Symptom Checker',
    symptoms_desc: 'Identify where you feel pain or discomfort using our interactive, picture-based assistant.',
    hospitals_title: 'Find Local Clinics & Hospitals',
    hospitals_desc: 'List of accessible government healthcare units and trusted partner hospitals near you.',
    appointments_title: 'My Doctor Bookings',
    appointments_desc: 'Manage your visits, check timings, and view digital confirmation slips.',
    camps_title: 'Upcoming Free Medical Camps',
    camps_desc: 'Health camps hosted by verified NGOs and healthcare providers. Zero charges for checkups.',
    prescriptions_title: 'My Digital Prescriptions',
    prescriptions_desc: 'Listen to spoken dosages and understand your medicine routines in your language.',
    history_title: 'My Secure Health Records',
    history_desc: 'Your vital information, health cards, and vaccination reports stored securely.',
    chat_title: 'Accessible Support Assistant',
    chat_desc: 'Have a quick question? Type or speak below to communicate with doctors or get automated assistance.',
    submit: 'Send',
    register: 'Register',
    register_camp: 'Register for Camp',
    call: 'Call',
    directions: 'Get Directions',
    book: 'Book Appointment',
    view_docs: 'View Doctors',
    registered: 'Registered successfully',
    confirm: 'Confirm',
    language: 'Language',
    emergency_phrases: 'Emergency Phrases',
    mic_speak: 'Speak',
  },
  te: {
    back: 'వెనుకకు',
    emergency_title: 'ఆపత్కాల సహాయ కేంద్రం',
    emergency_desc: 'మీకు లేదా మీ చుట్టుపక్కల వారికి అత్యవసర వైద్యం అవసరమైతే, సహాయం కోసం క్రింది బటన్ నొక్కండి.',
    symptoms_title: 'లక్షణాల తనిఖీ కేంద్రం',
    symptoms_desc: 'మా సులభమైన బొమ్మల సహాయంతో మీకు ఎక్కడ నొప్పి లేదా అసౌకర్యంగా ఉందో గుర్తించండి.',
    hospitals_title: 'సమీప ఆసుపత్రుల జాబితా',
    hospitals_desc: 'మీకు దగ్గరలో ఉన్న ఉచిత ప్రభుత్వ ఆరోగ్య కేంద్రాలు మరియు నమ్మకమైన ఆసుపత్రులు.',
    appointments_title: 'నా డాక్టర్ అపాయింట్‌మెంట్‌లు',
    appointments_desc: 'మీ డాక్టర్ల సందర్శన సమయాలు మరియు అపాయింట్‌మెంట్ రసీదులను ఇక్కడ చూడండి.',
    camps_title: 'రాబోయే ఉచిత వైద్య శిబిరాలు',
    camps_desc: 'స్వచ్ఛంద సంస్థలు (NGOలు) నిర్వహించే ఉచిత వైద్య పరీక్షల శిబిరాల వివరాలు.',
    prescriptions_title: 'నా డిజిటల్ మందుల చీటి',
    prescriptions_desc: 'మీ మందుల వాడకం వివరాలను మీ స్వంత భాషలో ఆడియో రూపంలో వినండి.',
    history_title: 'నా వైద్య ఆరోగ్య రికార్డులు',
    history_desc: 'మీ ఆరోగ్య కార్డులు, టీకాల వివరాలు మరియు పాత వైద్య రికార్డులు సురక్షితంగా ఇక్కడ ఉంటాయి.',
    chat_title: 'సహాయక వాయిస్ చాట్',
    chat_desc: 'ఏదైనా సందేహం ఉంటే, ఇక్కడ టైప్ చేయండి లేదా మాట్లాడి మీ భాషలో జవాబు పొందండి.',
    submit: 'పంపండి',
    register: 'నమోదు చేసుకోండి',
    register_camp: 'శిబిరానికి నమోదు',
    call: 'కాల్ చేయండి',
    directions: 'దారి కనుగొను',
    book: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    view_docs: 'వైద్యులను చూడండి',
    registered: 'నమోదు పూర్తయింది',
    confirm: 'ధృవీకరించండి',
    language: 'భాష',
    emergency_phrases: 'అత్యవసర పదబంధాలు',
    mic_speak: 'మాట్లాడండి',
  },
  hi: {
    back: 'पीछे जाएं',
    emergency_title: 'आपातकालीन सहायता केंद्र',
    emergency_desc: 'यदि आपको या आपके किसी करीबी को तुरंत इलाज की आवश्यकता है, तो सहायता के लिए नीचे दिए गए बटन को दबाएं।',
    symptoms_title: 'सरल लक्षण जाँच कर्ता',
    symptoms_desc: 'तस्वीरों की मदद से पहचानें कि आपको कहाँ दर्द या परेशानी महसूस हो रही है।',
    hospitals_title: 'आस-पास के अस्पताल और क्लीनिक',
    hospitals_desc: 'आपके निकटतम सरकारी स्वास्थ्य केंद्रों और विश्वसनीय अस्पतालों की सूची।',
    appointments_title: 'मेरे डॉक्टर अपॉइंटमेंट्स',
    appointments_desc: 'अपनी आगामी मुलाकातों का समय देखें और डिजिटल पर्ची डाउनलोड करें।',
    camps_title: 'आगामी मुफ्त चिकित्सा शिविर',
    camps_desc: 'एनजीओ और स्वास्थ्य संगठनों द्वारा आयोजित मुफ्त चिकित्सा जांच शिविरों की जानकारी।',
    prescriptions_title: 'मेरी डिजिटल दवा पर्ची',
    prescriptions_desc: 'अपनी दवाओं की खुराक और समय के बारे में अपनी भाषा में बोलकर सुनें।',
    history_title: 'मेरे सुरक्षित स्वास्थ्य रिकॉर्ड',
    history_desc: 'आपके टीकाकरण कार्ड, पुरानी रिपोर्ट और स्वास्थ्य जानकारी यहाँ सुरक्षित हैं।',
    chat_title: 'बहुभाषी सहायक चैट',
    chat_desc: 'कोई सवाल है? अपनी भाषा में पूछने के लिए यहाँ टाइप करें या बोलें।',
    submit: 'भेजें',
    register: 'पंजीकरण करें',
    register_camp: 'शिविर पंजीकरण',
    call: 'कॉल करें',
    directions: 'दिशा-निर्देश',
    book: 'अपॉइंटमेंट लें',
    view_docs: 'डॉक्टर देखें',
    registered: 'पंजीकरण सफल रहा',
    confirm: 'पुष्टि करें',
    language: 'भाषा',
    emergency_phrases: 'आपातकालीन वाक्य',
    mic_speak: 'बोलें',
  },
  kn: {
    back: 'ಹಿಂದಕ್ಕೆ',
    emergency_title: 'ತುರ್ತು ಚಿಕಿತ್ಸಾ ಸಹಾಯ',
    emergency_desc: 'ನಿಮಗೆ ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ನೆರವು ಬೇಕಾದರೆ, ದಯವಿಟ್ಟು ಕೆಳಗಿನ ಬಟನ್ ಒತ್ತಿ.',
    symptoms_title: 'ಲಕ್ಷಣಗಳ ತಪಾಸಣೆ',
    symptoms_desc: 'ಚಿತ್ರಗಳ ಸಹಾಯದಿಂದ ನಿಮ್ಮ ದೇಹದ ಯಾವ ಭಾಗದಲ್ಲಿ ನೋವು ಇದೆ ಎಂಬುದನ್ನು ಆರಿಸಿ.',
    hospitals_title: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    hospitals_desc: 'ನಿಮ್ಮ ಹತ್ತಿರದ ಉಚಿತ ಸರ್ಕಾರಿ ಆರೋಗ್ಯ ಕೇಂದ್ರಗಳು ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳ ಪಟ್ಟಿ.',
    appointments_title: 'ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    appointments_desc: 'ನಿಮ್ಮ ವೈದ್ಯರ ಭೇಟಿ ಸಮಯ ಮತ್ತು ವಿವರಗಳನ್ನು ಇಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.',
    camps_title: 'ಉಚಿತ ವೈದ್ಯಕೀಯ ಶಿಬಿರಗಳು',
    camps_desc: 'ಸಹಾಯ ಸಂಸ್ಥೆಗಳು ಆಯೋಜಿಸುವ ಉಚಿತ ಆರೋಗ್ಯ ಶಿಬಿರಗಳ ಮಾಹಿತಿ.',
    prescriptions_title: 'ನನ್ನ ಡಿಜಿಟಲ್ ಔಷಧಿ ಚೀಟಿ',
    prescriptions_desc: 'ನಿಮ್ಮ ಔಷಧಿಗಳ ಬಳಕೆಯ ವಿವರಗಳನ್ನು ನಿಮ್ಮದೇ ಭಾಷೆಯಲ್ಲಿ ಆಡಿಯೋ ಮೂಲಕ ಕೇಳಿ.',
    history_title: 'ನನ್ನ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    history_desc: 'ನಿಮ್ಮ ವ್ಯಾಕ್ಸಿನೇಷನ್ ಕಾರ್ಡ್ ಹಾಗೂ ಇತರ ವೈದ್ಯಕೀಯ ವರದಿಗಳು ಸುರಕ್ಷಿತವಾಗಿವೆ.',
    chat_title: 'ಸಹಾಯ ಕೇಂದ್ರ',
    chat_desc: 'ಏನಾದರೂ ಪ್ರಶ್ನೆಯಿದ್ದರೆ, ನಿಮ್ಮದೇ ಭಾಷೆಯಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಿ.',
    submit: 'ಕಳುಹಿಸು',
    register: 'ನೋಂದಾಯಿಸಿ',
    register_camp: 'ಶಿಬಿರಕ್ಕೆ ನೋಂದಣಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    directions: 'ಮಾರ್ಗಸೂಚಿ',
    book: 'ಬುಕ್ ಮಾಡಿ',
    view_docs: 'ವೈದ್ಯರನ್ನು ನೋಡಿ',
    registered: 'ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    language: 'ಭಾಷೆ',
    emergency_phrases: 'ತುರ್ತು ವಾಕ್ಯಗಳು',
    mic_speak: 'ಮಾತನಾಡಿ',
  },
  ta: {
    back: 'பின்னால்',
    emergency_title: 'அவசர உதவி மையம்',
    emergency_desc: 'உங்களுக்கு அவசர சிகிச்சை தேவைப்பட்டால், கீழே உள்ள பொத்தானை அழுத்தவும்.',
    symptoms_title: 'அறிகுறி கண்டறிதல்',
    symptoms_desc: 'படங்களின் உதவியுடன் உங்கள் உடலில் எங்கு வலி இருக்கிறது என்பதைத் தேர்ந்தெடுக்கவும்.',
    hospitals_title: 'அருகிலுள்ள மருத்துவமனைகள்',
    hospitals_desc: 'உங்களுக்கு அருகிலுள்ள அரசு சுகாதார நிலையங்கள் மற்றும் மருத்துவமனைகளின் பட்டியல்.',
    appointments_title: 'எனது முன்பதிவுகள்',
    appointments_desc: 'உங்கள் மருத்துவரைச் சந்திக்கும் நேரம் மற்றும் விபரங்களை இங்கே பாருங்கள்.',
    camps_title: 'இலவச மருத்துவ முகாம்கள்',
    camps_desc: 'தன்னார்வ அமைப்புகள் நடத்தும் இலவச மருத்துவ முகாம்களின் விபரங்கள்.',
    prescriptions_title: 'எனது மருத்துவ சீட்டு',
    prescriptions_desc: 'மருந்து உட்கொள்ளும் விபரங்களை உங்கள் சொந்த மொழியில் கேட்டுத் தெரிந்துகொள்ளுங்கள்.',
    history_title: 'எனது சுகாதார பதிவுகள்',
    history_desc: 'உங்கள் தடுப்பூசி அட்டைகள் மற்றும் முந்தைய மருத்துவ அறிக்கைகள் இங்கே பாதுகாப்பாக உள்ளன.',
    chat_title: 'உதவி குரல் அரட்டை',
    chat_desc: 'ஏதேனும் சந்தேகம் இருந்தால், உங்கள் மொழியில் டைப் செய்யவும் அல்லது பேசவும்.',
    submit: 'அனுப்பு',
    register: 'பதிவு செய்',
    register_camp: 'முகாமிற்கு பதிவு',
    call: 'அழைக்கவும்',
    directions: 'வழித்தடம்',
    book: 'முன்பதிவு செய்',
    view_docs: 'மருத்துவர்கள்',
    registered: 'பதிவு செய்யப்பட்டது',
    confirm: 'உறுதி செய்',
    language: 'மொழி',
    emergency_phrases: 'அவசரகால சொற்றொடர்கள்',
    mic_speak: 'பேசவும்',
  },
  ml: {
    back: 'പിന്നിലേക്ക്',
    emergency_title: 'അടിയന്തിര സഹായ കേന്ദ്രം',
    emergency_desc: 'നിങ്ങൾക്ക് അടിയന്തിര ചികിത്സ ആവശ്യമുണ്ടെങ്കിൽ താഴെയുള്ള ബട്ടൺ അമർത്തുക.',
    symptoms_title: 'രോഗലക്ഷണ പരിശോധന',
    symptoms_desc: 'നിങ്ങൾക്ക് എവിടെയാണ് വേദന അനുഭവപ്പെടുന്നത് എന്ന് ചിത്രങ്ങളുടെ സഹായത്തോടെ തിരഞ്ഞെടുക്കുക.',
    hospitals_title: 'അടുത്തുള്ള ആശുപത്രികൾ',
    hospitals_desc: 'നിങ്ങളുടെ അടുത്തുള്ള സർക്കാർ ആരോഗ്യ കേന്ദ്രങ്ങളുടെയും ആശുപത്രികളുടെയും വിവരങ്ങൾ.',
    appointments_title: 'എന്റെ അപ്പോയിന്റ്മെന്റുകൾ',
    appointments_desc: 'നിങ്ങളുടെ ഡോക്ടർ സന്ദർശന സമയങ്ങൾ ഇവിടെ പരിശോധിക്കുക.',
    camps_title: 'സൗജന്യ മെഡിക്കൽ ക്യാമ്പുകൾ',
    camps_desc: 'സന്നദ്ധ സംഘടനകൾ നടത്തുന്ന സൗജന്യ പരിശോധനാ ക്യാമ്പുകളുടെ വിവരങ്ങൾ.',
    prescriptions_title: 'എന്റെ ഡിജിറ്റൽ കുറിപ്പടി',
    prescriptions_desc: 'മരുന്നുകളുടെ വിവരങ്ങൾ നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ കേട്ടു മനസ്സിലാക്കുക.',
    history_title: 'എന്റെ ആരോഗ്യ രേഖകൾ',
    history_desc: 'നിങ്ങളുടെ വാക്സിനേഷൻ കാർഡും മുൻപത്തെ മെഡിക്കൽ റിപ്പോർട്ടുകളും സുരക്ഷിതമാണ്.',
    chat_title: 'സഹായ ചാറ്റ്',
    chat_desc: 'എന്തെങ്കിലും സംശയമുണ്ടെങ്കിൽ നിങ്ങളുടെ ഭാഷയിൽ ടൈപ്പ് ചെയ്യുകയോ സംസാരിക്കുകയോ ചെയ്യുക.',
    submit: 'അയക്കുക',
    register: 'രജിസ്റ്റർ ചെയ്യുക',
    register_camp: 'ക്യാമ്പ് രജിസ്ട്രേഷൻ',
    call: 'വിളിക്കുക',
    directions: 'വഴി കണ്ടെത്തുക',
    book: 'ബുക്ക് ചെയ്യുക',
    view_docs: 'ഡോക്ടർമാരെ കാണുക',
    registered: 'രജിസ്ട്രേഷൻ വിജയകരം',
    confirm: 'ഉറപ്പാക്കുക',
    language: 'ഭാഷ',
    emergency_phrases: 'അടിയന്തിര വാക്യങ്ങൾ',
    mic_speak: 'സംസാരിക്കുക',
  },
  bn: {
    back: 'ফিরে যান',
    emergency_title: 'জরুরী সহায়তা কেন্দ্র',
    emergency_desc: 'যদি আপনার বা আপনার পাশের কারো জরুরী চিকিৎসার প্রয়োজন হয়, তবে নিচের বোতামটি চাপুন।',
    symptoms_title: 'সহজ লক্ষণ পরীক্ষক',
    symptoms_desc: 'ছবির সাহায্যে চিহ্নিত করুন আপনার শরীরের কোথায় ব্যথা বা অস্বস্তি হচ্ছে।',
    hospitals_title: 'নিকটবর্তী হাসপাতাল',
    hospitals_desc: 'আপনার কাছাকাছি সরকারি স্বাস্থ্য কেন্দ্র এবং বিশ্বস্ত হাসপাতালের তালিকা।',
    appointments_title: 'আমার বুকিং সমূহ',
    appointments_desc: 'আপনার ডাক্তারের সাথে সাক্ষাতের সময় ও টিকিট এখানে দেখুন।',
    camps_title: 'বিনামূল্যে চিকিৎসা শিবির',
    camps_desc: 'এনজিও দ্বারা আয়োজিত বিনামূল্যে স্বাস্থ্য শিবিরের বিবরণ।',
    prescriptions_title: 'আমার ডিজিটাল প্রেসক্রিপশন',
    prescriptions_desc: 'আপনার ওষুধ খাওয়ার নিয়ম আপনার নিজের ভাষায় শুনুন।',
    history_title: 'আমার স্বাস্থ্য রেকর্ড',
    history_desc: 'আপনার টিকাকরণ কার্ড এবং পুরানো সমস্ত রিপোর্ট এখানে সুরক্ষিত আছে।',
    chat_title: 'সহায়ক চ্যাট',
    chat_desc: 'কোনো প্রশ্ন থাকলে নিজের ভাষায় টাইপ করুন বা মাইক্রোফোনে বলুন।',
    submit: 'পাঠান',
    register: 'রেজিস্ট্রেশন',
    register_camp: 'শিবির রেজিস্ট্রেশন',
    call: 'কল করুন',
    directions: 'দিকনির্দেশ',
    book: 'বুকিং করুন',
    view_docs: 'ডাক্তার দেখুন',
    registered: 'সফলভাবে নিবন্ধিত',
    confirm: 'নিশ্চিত করুন',
    language: 'ভাষা',
    emergency_phrases: 'জরুরি বাক্য',
    mic_speak: 'বলুন',
  },
  mr: {
    back: 'मागे जा',
    emergency_title: 'तातडीची मदत',
    emergency_desc: 'तुम्हाला किंवा जवळच्या कोणाला तातडीने वैद्यकीय मदतीची गरज असल्यास खालील बटण दाबा.',
    symptoms_title: 'लक्षणे तपासा',
    symptoms_desc: 'चित्रांच्या मदतीने तुम्हाला कुठे त्रास होत आहे ते निवडा.',
    hospitals_title: 'जवळची रुग्णालये',
    hospitals_desc: 'तुमच्या जवळील सरकारी दवाखाने आणि रुग्णालयांची यादी.',
    appointments_title: 'माझ्या भेटी (अपॉइंटमेंट्स)',
    appointments_desc: 'डॉक्टरांच्या भेटीची वेळ आणि माहिती येथे तपासा.',
    camps_title: 'मोफत वैद्यकीय शिबिर',
    camps_desc: 'स्वयंसेवी संस्थांनी आयोजित केलेल्या मोफत तपासणी शिबिरांची माहिती.',
    prescriptions_title: 'माझी डिजिटल औषध चिठ्ठी',
    prescriptions_desc: 'औषध घेण्याच्या वेळा तुमच्या स्वतःच्या भाषेत ऐका.',
    history_title: 'माझे आरोग्य रेकॉर्ड',
    history_desc: 'तुमचे लसीकरण पत्रक आणि जुने रिपोर्ट येथे सुरक्षित आहेत.',
    chat_title: 'मदत केंद्र',
    chat_desc: 'काही शंका असल्यास तुमच्या भाषेत लिहा किंवा बोला.',
    submit: 'पाठवा',
    register: 'नोंदणी करा',
    register_camp: 'शिबिर नोंदणी',
    call: 'कॉल करा',
    directions: 'दिशा दाखवा',
    book: 'अपॉइंटमेंट बुक करा',
    view_docs: 'डॉक्टर पहा',
    registered: 'नोंदणी यशस्वी',
    confirm: 'खात्री करा',
    language: 'भाषा',
    emergency_phrases: 'तातडीची वाक्ये',
    mic_speak: 'बोला',
  },
  or: {
    back: 'ଫେରିବା',
    emergency_title: 'ଆପାତକାଳୀନ ସହାୟତା',
    emergency_desc: 'ଯଦି ଆପଣଙ୍କୁ ତୁରନ୍ତ ଚିକିତ୍ସା ଆବଶ୍ୟକ ହୁଏ, ତେବେ ତଳେ ଥିବା ବଟନ୍ ଦବାନ୍ତୁ।',
    symptoms_title: 'ଲକ୍ଷଣ ଯାଞ୍ଚ କେନ୍ଦ୍ର',
    symptoms_desc: 'ଛବି ସାହାଯ୍ୟରେ ଶରୀରର କେଉଁ ଅଂଶରେ ଯନ୍ତ୍ରଣା ହେଉଛି ବାଛନ୍ତୁ।',
    hospitals_title: 'ନିକଟସ୍ଥ ହସ୍ପିଟାଲ୍',
    hospitals_desc: 'ଆପଣଙ୍କ ନିକଟରେ ଥିବା ସରକାରୀ ସ୍ୱାସ୍ଥ୍ୟ କେନ୍ଦ୍ର ଏବଂ ହସ୍ପିଟାଲ୍ ତାଲିକା।',
    appointments_title: 'ମୋର ଆପଏଣ୍ଟମେଣ୍ଟ',
    appointments_desc: 'ଡାକ୍ତରଙ୍କ ସହିତ ସାକ୍ଷାତ ସମୟ ଏଠାରେ ଯାଞ୍ଚ କରନ୍ତు।',
    camps_title: 'ମାଗଣା ସ୍ୱାସ୍ଥ୍ୟ ଶିବିର',
    camps_desc: 'ଏନଜିଓ ଦ୍ୱାରା ଆୟୋଜିତ ମାଗଣା ସ୍ୱାସ୍ଥ្យ ଶିବିର ବିବରଣୀ।',
    prescriptions_title: 'ମୋର ମେଡିସିନ୍ ପତ୍ର',
    prescriptions_desc: 'ଔଷଧ ଖାଇବାର ସମସ୍ତ ନିୟମ ଆପଣଙ୍କ ନିଜ ଭାଷାରେ ଶୁଣନ୍ତୁ।',
    history_title: 'ମୋର ସ୍ୱାସ୍ଥ្យ ରେକର୍ଡ',
    history_desc: 'ଆପଣଙ୍କର ଟୀକାକରଣ କାର୍ଡ ଏବଂ ପୁରୁଣା ରିପୋର୍ଟ ସୁରକ୍ଷିତ ଅଛି।',
    chat_title: 'ସହାୟତା ଚାଟ୍',
    chat_desc: 'କିଛି ପ୍ରଶ୍ନ ଥିଲେ ନିଜ ଭାଷାରେ ଟାଇପ୍ କରନ୍ତୁ କିମ୍ବା ମାଇକ୍ରୋଫୋନରେ କୁହନ୍ତୁ।',
    submit: 'ପଠାନ୍ତୁ',
    register: 'ପଞ୍ଜୀକରଣ',
    register_camp: 'ଶିବିର ପଞ୍जୀକରଣ',
    call: 'କଲ୍ କରନ୍ତు',
    directions: 'ମାର୍ଗଦର୍ଶନ',
    book: 'ବୁକିଂ କରନ୍ତు',
    view_docs: 'ଡାକ୍ତର ଦେଖନ୍ତು',
    registered: 'ସଫଳତାର ସହିତ ପଞ୍ଜିକୃତ',
    confirm: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
    language: 'ଭାଷା',
    emergency_phrases: 'ଆପାତକାଳୀନ ବାକ୍ୟ',
    mic_speak: 'କୁହନ୍ତୁ',
  },
  pa: {
    back: 'ਪਿੱਛੇ ਜਾਓ',
    emergency_title: 'ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ',
    emergency_desc: 'ਜੇਕਰ ਤੁਹਾਨੂੰ ਜਾਂ ਕਿਸੇ ਹੋਰ ਨੂੰ ਤੁਰੰਤ ਇਲਾਜ ਦੀ ਲੋੜ ਹੈ, ਤਾਂ ਹੇਠਾਂ ਦਿੱਤਾ ਬਟਨ ਦਬਾਓ।',
    symptoms_title: 'ਲੱਛਣਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    symptoms_desc: 'ਤਸਵੀਰਾਂ ਦੀ ਮਦਦ ਨਾਲ ਪਛਾਣੋ ਕਿ ਤੁਹਾਡੇ ਸਰੀਰ ਵਿੱਚ ਕਿੱਥੇ ਦਰਦ ਜਾਂ ਤਕਲੀਫ ਹੈ।',
    hospitals_title: 'ਨੇੜਲੇ ਹਸਪਤਾਲ',
    hospitals_desc: 'ਤੁਹਾਡੇ ਨੇੜਲੇ ਸਰਕਾਰੀ ਸਿਹਤ ਕੇਂਦਰਾਂ ਅਤੇ ਹਸਪਤਾਲਾਂ ਦੀ ਸੂਚੀ।',
    appointments_title: 'ਮੇਰੀਆਂ ਮੁਲਾਕਾਤਾਂ',
    appointments_desc: 'ਡਾਕਟਰਾਂ ਨਾਲ ਆਪਣੀ ਮੁਲਾਕਾਤ ਦਾ ਸਮਾਂ ਇੱਥੇ ਦੇਖੋ।',
    camps_title: 'ਮੁਫ਼ਤ ਮੈਡੀਕਲ ਕੈਂਪ',
    camps_desc: 'ਸਵੈ-ਸੇਵੀ ਸੰਸਥਾਵਾਂ ਦੁਆਰਾ ਲਗਾਏ ਜਾਣ ਵਾਲੇ ਮੁਫ਼ਤ ਸਿਹਤ ਕੈਂਪਾਂ ਦੀ ਜਾਣਕਾਰੀ।',
    prescriptions_title: 'ਮੇਰੀ ਡਿਜੀਟਲ ਪਰਚੀ',
    prescriptions_desc: 'ਦਵਾਈ ਲੈਣ ਦੇ ਨਿਯਮ ਅਤੇ ਸਮਾਂ ਆਪਣੀ ਖੁਦ ਦੀ ਬੋਲੀ ਵਿੱਚ ਸੁਣੋ।',
    history_title: 'ਮੇਰਾ ਸਿਹਤ ਰਿਕਾਰਡ',
    history_desc: 'ਤੁਹਾਡਾ ਟੀਕਾਕਰਨ ਕਾਰਡ ਅਤੇ ਪੁਰਾਣੀਆਂ ਰਿਪੋਰਟਾਂ ਇੱਥੇ ਸੁਰੱਖਿਅਤ ਹਨ।',
    chat_title: 'ਮਦਦਗਾਰ ਚੈਟ',
    chat_desc: 'ਕੋਈ ਸਵਾਲ ਹੈ? ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਲਿਖੋ ਜਾਂ ਮਾਈਕ੍ਰੋਫੋਨ ਰਾਹੀਂ ਬੋਲੋ।',
    submit: 'ਭੇਜੋ',
    register: 'ਰਜਿਸਟਰ ਕਰੋ',
    register_camp: 'ਕੈਂਪ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    call: 'ਕਾਲ ਕਰੋ',
    directions: 'ਦਿਸ਼ਾ ਨਿਰਦੇਸ਼',
    book: 'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    view_docs: 'ਡਾਕਟਰ ਦੇਖੋ',
    registered: 'ਰਜਿਸਟਰੇਸ਼ਨ ਸਫਲ ਰਹੀ',
    confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ',
    language: 'ਭਾਸ਼ਾ',
    emergency_phrases: 'ਐਮਰਜੈਂਸੀ ਵਾਕ',
    mic_speak: 'ਬੋਲੋ',
  },
};
